### ISSUE TITLE
IronMq dependency removed from native QueueServiceProvider, Causing error on laravel v5.2 and onwards

### ISSUE THREAD

**Issue by abhpatidar** [pafelin/laravel-gearman#13]
registerIronConnector function not present anymore in QueueServiceProvider class. 

Request you to remove 'Iron' from array  in registerConnectors in class GearmanServiceProvider class.

![screenshot 2016-02-21 10 38 04](https://cloud.githubusercontent.com/assets/4954799/13201071/42a33ba6-d887-11e5-8e1e-7653a4eb89d5.png)

**Comment by pafelin** [comment]
Added. 

Thanks for reporting it :) 

The package was created when the latest version of laravel was 4.1 and I would recommend you to use another queue manager. Try RabbitMQ or Beanstalkd. 

Gearman is awesome, but the driver for it for php isn't allowing you to use all Gearman features. Beanstalkd is my personal choice because it is simple and it has great monitoring tool.
