### ISSUE TITLE
Worker in daemon mode

### ISSUE THREAD

**Issue by sebo** [pafelin/laravel-gearman#15]
Hi

I use laravel 5.2. When I run the queue with the following command 

php artisan queue:work  --daemon

gearadmin --status shows after some time that there are 200 instances of the worker running.

Also I'm seeing "1 minutes have elapsed, expiring." 

That doesn't seem to be right?

Can you help?

Thanks

Sebo

**Comment by sebo** [comment]
I'm also seeing this error:

ProcessTimedOutException

**Comment by pafelin** [comment]
Hi 

Correct, this implementation does not support the --daemon option. You don't need it with Gearman. 

Use: php artisan queue:listen 
--daemon was added for queue storages that use lots of resources, the implementation of Gearman doesn't use. 

Also if you can avoid using gearman I would advice you to do so. Best would be to update to beanstalkd (since it is the closest to gearman) 
Otherwise good queue/ampq is rabbitmq but in most cases it is overkill. You need to know that for rabbitmq you definitely need to use --daemon.

Best

**Comment by sebo** [comment]
Thanks for the information!
